### ISSUE TITLE
🐛 String mismatch encountered while superimposing style sections: '↵' vs 'k''

### ISSUE THREAD

**Issue by aral** [dandavison/delta#1172]
![image](https://user-images.githubusercontent.com/41798/186744278-aeadba98-48e7-4c10-a346-41e6346423fd.png)

Error:

```
thread 'main' panicked at 'String mismatch encountered while superimposing style sections: '↵' vs 'k'', /var/home/aral/.cargo/registry/src/github.com-1ecc6299db9ec823/git-delta-0.12.1/src/paint.rs:922
```

Is caused by the following diff:

```diff
diff --git a/src/production/Server.js b/src/production/Server.js
index c43305e..501b6bd 100644
--- a/src/production/Server.js
+++ b/src/production/Server.js
@@ -162,7 +162,12 @@ export default class Server extends EventTarget {
 
     this.server = https.createServer(this.options, handler)
     this.server.listen(443, () => {
-      console.info(`😸️ Kitten\n\n  💾 ${chalk.bold('Serving:')} ${process.env.basePath}\n  🌍 ${chalk.bold('At:')} https://${this.hostname}\n`)
+      console.info(
+        "😸️ Kitten\n\n" +
+        `📂 ${chalk.bold('Serving:')} ${process.env.basePath}\n` +
+        `🌍 ${chalk.bold('At:')} https://${this.hostname}\n` +
+        `💾 ${chalk.bold('Database:')} ${databaseDirectory}\n`
+      )
     })
   }
```

Full backtrace:

<details>

```
   0:     0x5615ea0d855d - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5615ea0d855d - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5615ea0d855d - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5615ea0d855d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5615ea0ffa0c - core::fmt::write::he803f0f418caf762
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x5615ea0d3608 - std::io::Write::write_fmt::h70bc45872f37e7bb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x5615ea0da8c7 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5615ea0da8c7 - std::sys_common::backtrace::print::h359300b4a7fccf65
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5615ea0da8c7 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x5615ea0da590 - std::panicking::default_hook::h03ca0f22e1d2d25e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x5615ea0db019 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
  11:     0x5615ea0dad07 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  12:     0x5615ea0d8a24 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x5615ea0daa19 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  14:     0x5615e9e2b283 - core::panicking::panic_fmt::he1bbc7336d49a357
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  15:     0x5615e9ea83d6 - delta::paint::Painter::paint_line::hb3721735e8d2124e
  16:     0x5615e9e979b2 - delta::features::side_by_side::paint_minus_or_plus_panel_line::he4d04b2089c3a767
  17:     0x5615e9e960d7 - delta::features::side_by_side::paint_minus_and_plus_lines_side_by_side::h3b475cea9c985446
  18:     0x5615e9ea996f - delta::paint::paint_minus_and_plus_lines::hb0a45641da2228c7
  19:     0x5615e9ea552e - delta::paint::Painter::paint_buffered_minus_and_plus_lines::hdea4ff1781b92caf
  20:     0x5615e9f109fc - delta::handlers::hunk::<impl delta::delta::StateMachine>::handle_hunk_line::he943c6f38e0b0637
  21:     0x5615e9f0af9f - delta::delta::delta::hfda5e87889555fc8
  22:     0x5615e9f1d6c6 - delta::main::hdecd10abd1b8adc6
  23:     0x5615e9ebd2b3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbf18c596260c27ce
  24:     0x5615e9ed010d - std::rt::lang_start::{{closure}}::h9b88a567912c19ee
  25:     0x5615ea0d7c41 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb7014f43484a8b4e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:259:13
  26:     0x5615ea0d7c41 - std::panicking::try::do_call::h7bc9dc436daeb8c7
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  27:     0x5615ea0d7c41 - std::panicking::try::h653d68a27ff5f175
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  28:     0x5615ea0d7c41 - std::panic::catch_unwind::h9d739f9f59895e68
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  29:     0x5615ea0d7c41 - std::rt::lang_start_internal::{{closure}}::hf006f2bc7ce22bbe
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:48
  30:     0x5615ea0d7c41 - std::panicking::try::do_call::hfb39d6df61a2e69f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  31:     0x5615ea0d7c41 - std::panicking::try::h13e2d225134958ac
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  32:     0x5615ea0d7c41 - std::panic::catch_unwind::h3bd49b5a5dfb1a50
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  33:     0x5615ea0d7c41 - std::rt::lang_start_internal::h2ba92edce36c035e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:20
  34:     0x5615e9f1ee02 - main
  35:     0x7fcce07a5550 - __libc_start_call_main
  36:     0x7fcce07a5609 - __libc_start_main_impl
  37:     0x5615e9e2bab5 - _start
```

</details>

**Comment by th1000s** [comment]
I can't reproduce this anymore with the current delta version. However the bat reproducer linked above is now using the same `bat` and `syntect` version as delta and (of course) it still splits off of the variant selector.

The bat version of delta was updated to 22.1 just 3 months ago, so maybe that somehow fixed it?
