### ISSUE TITLE
🐛 delta `panick`s when HOME is unset (on RHEL 8, with musl binary)

### ISSUE THREAD

**Issue by phil-blain** [dandavison/delta#1270]
- [X] Please include the raw text output from git, so that we can reproduce the problem.
      (You can use `git --no-pager` to produce the raw text output.)

N/A

- [X] A screenshot of Delta's output is often helpful also.

N/A

---

When testing command invocations, I often use `HOME= some-command ...` so that my specific configuration for `some-command` is not used (this is useful to test bug reports and come up with reproducible bug reports ;)

This does not work with delta:

~~~bash
$ ./delta-0.15.1-x86_64-unknown-linux-musl/delta --version
0.15.1
$ HOME= ./delta-0.15.1-x86_64-unknown-linux-musl/delta --version
thread 'main' panicked at 'Could not get home directory', src/utils/bat/dirs.rs:40:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
~~~

Adding `RUST_BACKTRACE=full` does not give helpful details for the musl binary from the GitHub releases.

**Comment by phil-blain** [comment]
I found I can get the same result with `--no-gitconfig`, but still it would be nice if it didn't panick as above :)

**Comment by dandavison** [comment]
Hm, I'm failing to reproduce this (MacOS). More concerningly, at first glance, I don't see how it can happen! The `new()` function always returns `Some(..)` hence `panic(...)` should never be called. https://github.com/dandavison/delta/blob/ce6448f9c3e8e61d06127c62ee775f9372bc1c34/src/utils/bat/dirs.rs#L40

**Comment by phil-blain** [comment]
Hi @dandavison :) thanks for your answer. Indeed, it does not happen on macOS for me either. 

It also does not happen on Ubuntu 22 with either the `delta-0.15.1-x86_64-unknown-linux-gnu` binary or the `*-musl` one.

It does not happen either on Ubuntu 18 or 20 with the  `*-musl` binary (the  `*-gnu` binary does not work on these platforms, I get errors from `/lib/x86_64-linux-gnu/libc.so.6` about ``version `GLIBC_2.N' not found`` with `N=28,29,32,33,34` for Ubuntu 18 and `N=32,33,34` for Ubuntu 20). 

But it _does_ happen on RHEL 8, which is the distro I use,  with the `musl` binary (the `gnu` binary fails as above with `N=29,32,33,34`).

**Comment by dandavison** [comment]
Hm, that's exciting. Does it happen to bat also?

**Comment by phil-blain** [comment]
Yes, on the RHEL8 system I'm testing on, it also happens with the `bat-v0.22.1` musl binary:
```
$ HOME= ./bat-v0.22.1-x86_64-unknown-linux-musl/bat  --version
thread 'main' panicked at 'Could not get home directory', src/bin/bat/directories.rs:72:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

but not with the gnu binary. And (sidenote), the musl and gnu bat binaries work correctly for Ubuntu 18-22 (no error message relating to `GLIBC_2.*`).

One other "exciting" thing is that I am not yet able to reproduce on my WSL 2 RHEL 8 instance (WSL=Windows Subsystem for Linux).

**Comment by phil-blain** [comment]
So I compiled myself a debug version of delta: https://github.com/phil-blain/delta/releases/tag/0.15.2 and took a look at what happens in GDB:
~~~
HOME= gdb -d ~/code/delta \
  -ex 'handle SIG34 nostop' \
  -ex 'b BatProjectDirs::new' \
  -ex run \
  --args delta-0.15.2-x86_64-unknown-linux-musl/delta --version
~~~

I _think_ (it's my first experience with Rust) that the panic happens because `map` is called on `cache_dir_op` which is `None` since HOME is unset.

Here is my debugging session:
~~~
gdb: warning: Couldn't determine a path for the index cache directory.
Reading symbols from delta-0.15.2-x86_64-unknown-linux-musl/delta...
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /fs/homeu2/eccc/cmd/ords/cmde/phb001/logiciels/delta-0.15.2-x86_64-unknown-linux-musl/delta.
Use `info auto-load python-scripts [REGEXP]' to list them.
Signal        Stop      Print   Pass to program Description
SIG34         No        Yes     Yes             Real-time event 34
Breakpoint 1 at 0x132ed0: file src/utils/bat/dirs.rs, line 26.
Starting program: /fs/homeu2/eccc/cmd/ords/cmde/phb001/logiciels/delta-0.15.2-x86_64-unknown-linux-musl/delta --version
[New LWP 3505583]
[New LWP 3505584]

Thread 1 "delta" received signal SIG34, Real-time event 34.

Thread 3 "ctrl-c" received signal SIG34, Real-time event 34.

Thread 1 "delta" hit Breakpoint 1, delta::utils::bat::dirs::BatProjectDirs::new () at src/utils/bat/dirs.rs:26
warning: Source file is more recent than executable.
26              let cache_dir_op = dirs_next::cache_dir();
(gdb) n
28              let cache_dir = cache_dir_op.map(|d| d.join("bat"))?;
(gdb) p cache_dir_op
$1 = core::option::Option<std::path::PathBuf>::None
(gdb) n
[LWP 3505583 exited]
28              let cache_dir = cache_dir_op.map(|d| d.join("bat"))?;
(gdb) n
31          }
(gdb) n
thread 'main' panicked at 'Could not get home directory', src/utils/bat/dirs.rs:40:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[LWP 3505584 exited]
[Inferior 1 (process 3505563) exited with code 0145]
(gdb) quit
~~~
Notice one thread exits after the line `let cache_dir = cache_dir_op.map(|d| d.join("bat"))?;` is executed, but the panic is triggered when leaving the function...

**Comment by phil-blain** [comment]
So on my WSL system (which does not panic), `cache_dir_op` is _not_ `None`:

~~~
(gdb) p cache_dir_op
$2 = core::option::Option<std::path::PathBuf>::Some(std::path::PathBuf {inner: std::ffi::os_str::OsString {inner: std::sys::unix::os_str::Buf {inner: alloc::vec::Vec<u8, alloc::alloc::Global> {buf: alloc::raw_vec::RawVec<u8, alloc::alloc::Global> {ptr: core::ptr::unique::Unique<u8> {pointer: core::ptr::non_null::NonNull<u8> {pointer: 0x90dcda0 "\230:\355\b\000"}, _marker: core::marker::PhantomData<u8>}, cap: 28, alloc: alloc::alloc::Global}, len: 21}}}})
~~~

And I _think_ this is because on the system where I hit the panic, my home directory is a symlink. 

-  [`dirs_next::cache_dir` is a simple wrapper around `sys::cache_dir`](https://docs.rs/dirs-next/latest/src/dirs_next/lib.rs.html#77-79)
- [`sys` is `dirs_next::lin` on Linux](https://docs.rs/dirs-next/latest/src/dirs_next/lib.rs.html#31-33)
- [`dirs_next::lin::cache_dir` calls `dirs_next::lin::home_dir`](https://docs.rs/dirs-next/latest/src/dirs_next/lin.rs.html#5)
- [`dirs_next::lin::home_dir` calls `dirs_sys_next::home_dir`](https://docs.rs/dirs-next/latest/src/dirs_next/lin.rs.html#4)
- [`dirs_sys_next::home_dir` calls `libc::getpwuid_r`](https://docs.rs/dirs-sys-next/latest/src/dirs_sys_next/lib.rs.html#28-60) if `HOME` is empty to query the system database
- this calls returns `None` on the affected system. I think that'a bug; it should find my home directory in the database...
