### ISSUE TITLE
🐛 ripgrep JSON output causes panic with UTF character

### ISSUE THREAD

**Issue by mmottl** [dandavison/delta#1679]
Consider the following text file containing a UTF character followed by newline:

```zsh
❯ cat foo.txt
━
```

Here is the hex dump for clarity:

```zsh
❯ xxd -p foo.txt
e294810a
```

Delta will interpret regular `rg` output just fine:

```zsh
❯ rg "" foo.txt | delta
━
```

But it will panic when using JSON output:

```zsh
❯ rg --json "" foo.txt | RUST_BACKTRACE=1 delta
thread 'main' panicked at src/handlers/grep.rs:389:50:
byte index 1 is not a char boundary; it is inside '━' (bytes 0..3) of `━`
stack backtrace:
• foo.txt
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::str::slice_error_fail_rt
   3: core::str::slice_error_fail
   4: delta::handlers::grep::make_style_sections
   5: delta::handlers::grep::<impl delta::delta::StateMachine>::handle_grep_line
   6: delta::delta::delta
   7: delta::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by DanSM-5** [comment]
I am observing the same issue. To me it is happening when the result is too open like an empty string `""` a dot `"."` or a match with many optional characters `com.*`. Unfortunately using delta without the output of ripgrep with `--json` makes not much difference from the regular ripgrep output.

**Comment by dandavison** [comment]
@DanSM-5 can you post some `rg --json` output that makes delta crash?

**Comment by dandavison** [comment]
@mmottl thanks! I certainly agree that delta shouldn't panic. In order to determine the best code change, it would help me to know -- are you aware of any more "realistic" examples that cause delta to crash? The one you posted is searching for an empty regex. I'm curious whether there are non-empty regexes that cause ripgre to output byte offsets that do not align with utf-8 boundaries?

**Comment by mmottl** [comment]
@dandavison It's been a while that I ran into this issue. Obviously, I tried to come up with the smallest test case possible. I believe I ran into it when using the following script together with `fzf` as a user interface for searching through large repos with nicely colored output and exact position information:

```sh
#!/usr/bin/env bash

# Ripgrep with suitable arguments
rg_cmd() {
  rg --line-number --column --no-heading --smart-case --sort=path \
    --color=always "$@"
}

# Double ripgrep and delta with suitable arguments
paste \
  <(rg_cmd "$@" | sed -e 's/^\([^:]*:[^:]*:[^:]*:\).*/\1/') \
  <(rg_cmd --json "$@" | delta --grep-output-type classic | cut -d: -f4-)
```

I know it happened on rare occasions, but since I switched to different search tools, I don't remember what kind of searches caused the problem.

**Comment by DanSM-5** [comment]
I found that it had to do with combination of `\r\n` and `\n` in the lines

Command:

```bash
rg --pretty --context 5 --json 'https.*' test.txt | delta
```

Where test.txt is:

```
https://www.google.com/search?q=weather&zx=1740103933062&no_sw_cr=1
https://github.com/dandavison/delta/issues/1679#issuecomment-2673131255
```

**NOTE**: put a carriage return at the end of the first url.

Output:

```json
{
  "type": "begin",
  "data": {
    "path": {
      "text": "test.txt"
    }
  }
}
{
  "type": "match",
  "data": {
    "path": {
      "text": "test.txt"
    },
    "lines": {
      "text": "https://www.google.com/search?q=weather&zx=1740103933062&no_sw_cr=1\r\n"
    },
    "line_number": 1,
    "absolute_offset": 0,
    "submatches": [
      {
        "match": {
          "text": "https://www.google.com/search?q=weather&zx=1740103933062&no_sw_cr=1\r"
        },
        "start": 0,
        "end": 68
      }
    ]
  }
}
{
  "type": "match",
  "data": {
    "path": {
      "text": "test.txt"
    },
    "lines": {
      "text": "https://github.com/dandavison/delta/issues/1679#issuecomment-2673131255\n"
    },
    "line_number": 2,
    "absolute_offset": 69,
    "submatches": [
      {
        "match": {
          "text": "https://github.com/dandavison/delta/issues/1679#issuecomment-2673131255"
        },
        "start": 0,
        "end": 71
      }
    ]
  }
}
{
  "type": "end",
  "data": {
    "path": {
      "text": "test.txt"
    },
    "binary_offset": null,
    "stats": {
      "elapsed": {
        "secs": 0,
        "nanos": 39500,
        "human": "0.000039s"
      },
      "searches": 1,
      "searches_with_match": 1,
      "bytes_searched": 141,
      "bytes_printed": 668,
      "matched_lines": 2,
      "matches": 2
    }
  }
}
{
  "data": {
    "elapsed_total": {
      "human": "0.015543s",
      "nanos": 15542600,
      "secs": 0
    },
    "stats": {
      "bytes_printed": 668,
      "bytes_searched": 141,
      "elapsed": {
        "human": "0.000039s",
        "nanos": 39500,
        "secs": 0
      },
      "matched_lines": 2,
      "matches": 2,
      "searches": 1,
      "searches_with_match": 1
    }
  },
  "type": "summary"
}
```

Error: RUST_BACKTRACE=full

```
rg --pretty --context 5 --json 'https.*' test.txt | delta
thread 'main' panicked at src\handlers\grep.rs:387:42:
byte index 68 is out of bounds of `https://www.google.com/search?q=weather&zx=1740103933062&no_sw_cr=1`
stack backtrace:
   0:     0x7ff6378d235d - onig_get_start_by_callout_args
   1:     0x7ff6378f2ab9 - onig_get_start_by_callout_args
   2:     0x7ff6378ce091 - onig_get_start_by_callout_args
   3:     0x7ff6378d4657 - onig_get_start_by_callout_args
   4:     0x7ff6378d4249 - onig_get_start_by_callout_args
   5:     0x7ff6378d4d92 - onig_get_start_by_callout_args
   6:     0x7ff6378d4bd6 - onig_get_start_by_callout_args
   7:     0x7ff6378d2ccf - onig_get_start_by_callout_args
   8:     0x7ff6378d47b6 - onig_get_start_by_callout_args
   9:     0x7ff637a15fb4 - onigenc_strlen_null
  10:     0x7ff6378f5c17 - onig_get_start_by_callout_args
  11:     0x7ff637a16678 - onigenc_strlen_null
  12:     0x7ff6377098d1 - <unknown>
  13:     0x7ff6375f0fa4 - <unknown>
  14:     0x7ff6375e92c2 - <unknown>
  15:     0x7ff6376f4f43 - <unknown>
  16:     0x7ff6376829a6 - <unknown>
  17:     0x7ff637702b9a - <unknown>
  18:     0x7ff6378c6369 - onig_get_start_by_callout_args
  19:     0x7ff6376f761c - <unknown>
  20:     0x7ff6379fe9ac - onigenc_strlen_null
  21:     0x7ff8ed84259d - BaseThreadInitThunk
  22:     0x7ff8efa6af38 - RtlUserThreadStart
```

Version

```bash
delta --version
delta 0.18.2
```
