### ISSUE TITLE
Error: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by mgred** [dandavison/delta#29]
I encounterd the following Error using `git diff`:
```shell
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

The full output looks like:
![Screenshot 2019-10-16 at 11 58 52](https://user-images.githubusercontent.com/2325260/66909056-6964d380-f00c-11e9-862a-910020dd669d.png)

The shown diff ist wrong, the actual is:
![Screenshot 2019-10-16 at 11 59 13](https://user-images.githubusercontent.com/2325260/66909131-8699a200-f00c-11e9-8644-5beb70677c93.png)

When I switch branch with different files changed and e.g. call `git diff origin/master` everyting works as expected.

BTW: I built `delta` myself with `cargo build --release`

**Comment by dandavison** [comment]
Thanks @mgred! Would you be able to do any of the following?

1. Point me to a public git repo (and commit) on which this error occurs?

2. Post the output of `git show` on a single commit which you can share publicly and generates the error?

3. `export RUST_BACKTRACE=1` and repeat the command and post the stack trace?

**Comment by mgred** [comment]
@dandavison thanks for troubleshooting this.

 
>     1. Point me to a public git repo (and commit) on which this error occurs?

I'm using https://github.com/sinonjs/samsam @ `master`. When running e.g. `git diff HEAD~1`
![Screenshot 2019-10-16 at 19 55 07](https://user-images.githubusercontent.com/2325260/66945182-e618a180-f04e-11e9-8ef5-b81130cf5ee5.png)


```shell
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

package-lock.json
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
502
     "array-from": {
       "version": "2.1.1",
       "resolved": "https://registry.npmjs.org/array-from/-/array-from-2.1.1.tgz",
```
> 
>     2. Post the output of `git show` on a single commit which you can share publicly and generates the error?

`git show 8e2f652`

![Screenshot 2019-10-16 at 19 57 33](https://user-images.githubusercontent.com/2325260/66945369-3e4fa380-f04f-11e9-8c1f-957d23aa52f6.png)

> 
>     3. `export RUST_BACKTRACE=1` and repeat the command and post the stack trace?

`git show 8e2f652 | delta &> git-show`

```shell
commit 8e2f652fe2e3ec54545e4b41b41757c0c33dea00
Author: Morgan Roderick <morgan@roderick.dk>
Date:   Wed Oct 16 12:23:46 2019 +0100

    Add test for issue #71


[34madded: lib/issues.test.js[0m
[34m────────────────────────────────────────────────────────────────────────────────[0m
[34m1[0m
[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m[38;2;230;219;116m"use strict"[48;2;0;40;0m[38;2;248;248;242m;[48;2;0;40;0m                                                                
[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m                                                                             
[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m[38;2;102;217;239mvar[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m[38;2;255;255;255mjQuery[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m[38;2;249;38;114m=[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m[38;2;102;217;239mrequire[48;2;0;40;0m[38;2;248;248;242m([48;2;0;40;0m[38;2;230;219;116m"jquery"[48;2;0;40;0m[38;2;248;248;242m);[48;2;0;40;0m                                              
[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m[38;2;102;217;239mvar[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m[38;2;255;255;255massert[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m[38;2;249;38;114m=[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m[38;2;102;217;239mrequire[48;2;0;40;0m[38;2;248;248;242m([48;2;0;40;0m[38;2;230;219;116m"@sinonjs/referee"[48;2;0;40;0m[38;2;248;248;242m).[48;2;0;40;0m[38;2;255;255;255massert[48;2;0;40;0m[38;2;248;248;242m;[48;2;0;40;0m                             
[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m[38;2;102;217;239mvar[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m[38;2;255;255;255mrefute[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m[38;2;249;38;114m=[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m[38;2;102;217;239mrequire[48;2;0;40;0m[38;2;248;248;242m([48;2;0;40;0m[38;2;230;219;116m"@sinonjs/referee"[48;2;0;40;0m[38;2;248;248;242m).[48;2;0;40;0m[38;2;255;255;255mrefute[48;2;0;40;0m[38;2;248;248;242m;[48;2;0;40;0m                             
[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m                                                                             
[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m[38;2;102;217;239mvar[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m[38;2;255;255;255msamsam[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m[38;2;249;38;114m=[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m[38;2;102;217;239mrequire[48;2;0;40;0m[38;2;248;248;242m([48;2;0;40;0m[38;2;230;219;116m"./samsam"[48;2;0;40;0m[38;2;248;248;242m);[48;2;0;40;0m                                            
[48;2;0;40;0m[38;2;248;248;242m [48;2;0;40;0m                                                                             
[48;2;0;40;0m[38;2;248;248;242m describe([48;2;0;40;0m[38;2;230;219;116m"issues"[48;2;0;40;0m[38;2;248;248;242m, [48;2;0;40;0m[38;2;102;217;239mfunction[48;2;0;40;0m[38;2;248;248;242m()[48;2;0;40;0m[38;2;166;226;46m {[48;2;0;40;0m                                              
[48;2;0;40;0m[38;2;166;226;46m     describe([48;2;0;40;0m[38;2;230;219;116m"issue #71"[48;2;0;40;0m[38;2;166;226;46m, [48;2;0;40;0m[38;2;102;217;239mfunction[48;2;0;40;0m[38;2;166;226;46m() {[48;2;0;40;0m                                       
[48;2;0;40;0m[38;2;166;226;46m         before([48;2;0;40;0m[38;2;102;217;239mfunction[48;2;0;40;0m[38;2;166;226;46m() {[48;2;0;40;0m                                                  
[48;2;0;40;0m[38;2;166;226;46m             [48;2;0;40;0m[38;2;249;38;114mif[48;2;0;40;0m[38;2;166;226;46m ([48;2;0;40;0m[38;2;249;38;114mtypeof[48;2;0;40;0m[38;2;166;226;46m [48;2;0;40;0m[38;2;166;226;46mwindow[48;2;0;40;0m[38;2;166;226;46m [48;2;0;40;0m[38;2;249;38;114m===[48;2;0;40;0m[38;2;166;226;46m [48;2;0;40;0m[38;2;230;219;116m"undefined"[48;2;0;40;0m[38;2;166;226;46m) {[48;2;0;40;0m                             
[48;2;0;40;0m[38;2;166;226;46m                 [48;2;0;40;0m[38;2;102;217;239mthis[48;2;0;40;0m[38;2;166;226;46m.skip();[48;2;0;40;0m                                                 
[48;2;0;40;0m[38;2;166;226;46m             }[48;2;0;40;0m                                                                
[48;2;0;40;0m[38;2;166;226;46m         });[48;2;0;40;0m                                                                  
[48;2;0;40;0m[38;2;166;226;46m [48;2;0;40;0m                                                                             
[48;2;0;40;0m[38;2;166;226;46m         context([48;2;0;40;0m[38;2;230;219;116m"when comparing jQuery objects"[48;2;0;40;0m[38;2;166;226;46m, [48;2;0;40;0m[38;2;102;217;239mfunction[48;2;0;40;0m[38;2;166;226;46m() {[48;2;0;40;0m                
[48;2;0;40;0m[38;2;166;226;46m             it([48;2;0;40;0m[38;2;230;219;116m"should not throw"[48;2;0;40;0m[38;2;166;226;46m, [48;2;0;40;0m[38;2;102;217;239mfunction[48;2;0;40;0m[38;2;166;226;46m() {[48;2;0;40;0m                              
[48;2;0;40;0m[38;2;166;226;46m                 [48;2;0;40;0m[38;2;255;255;255mrefute[48;2;0;40;0m[38;2;166;226;46m.exception([48;2;0;40;0m[38;2;102;217;239mfunction[48;2;0;40;0m[38;2;166;226;46m() {[48;2;0;40;0m                                
[48;2;0;40;0m[38;2;166;226;46m                     [48;2;0;40;0m[38;2;255;255;255msamsam[48;2;0;40;0m[38;2;166;226;46m.deepEqual(jQuery([48;2;0;40;0m[38;2;230;219;116m"body"[48;2;0;40;0m[38;2;166;226;46m), jQuery([48;2;0;40;0m[38;2;230;219;116m"body"[48;2;0;40;0m[38;2;166;226;46m));[48;2;0;40;0m        
[48;2;0;40;0m[38;2;166;226;46m                 });[48;2;0;40;0m                                                          
[48;2;0;40;0m[38;2;166;226;46m             });[48;2;0;40;0m                                                              
[48;2;0;40;0m[38;2;166;226;46m         });[48;2;0;40;0m                                                                  
[48;2;0;40;0m[38;2;166;226;46m [48;2;0;40;0m                                                                             
[48;2;0;40;0m[38;2;166;226;46m         context([48;2;0;40;0m[38;2;230;219;116m"when comparing different jQuery objects"[48;2;0;40;0m[38;2;166;226;46m, [48;2;0;40;0m[38;2;102;217;239mfunction[48;2;0;40;0m[38;2;166;226;46m() {[48;2;0;40;0m      
[48;2;0;40;0m[38;2;166;226;46m             it([48;2;0;40;0m[38;2;230;219;116m"should return false"[48;2;0;40;0m[38;2;166;226;46m, [48;2;0;40;0m[38;2;102;217;239mfunction[48;2;0;40;0m[38;2;166;226;46m() {[48;2;0;40;0m                           
[48;2;0;40;0m[38;2;166;226;46m                 [48;2;0;40;0m[38;2;255;255;255massert[48;2;0;40;0m[38;2;166;226;46m.isFalse([48;2;0;40;0m                                              
[48;2;0;40;0m[38;2;166;226;46m                     [48;2;0;40;0m[38;2;255;255;255msamsam[48;2;0;40;0m[38;2;166;226;46m.deepEqual(jQuery([48;2;0;40;0m[38;2;230;219;116m"head"[48;2;0;40;0m[38;2;166;226;46m), jQuery([48;2;0;40;0m[38;2;230;219;116m"body"[48;2;0;40;0m[38;2;166;226;46m))[48;2;0;40;0m         
[48;2;0;40;0m[38;2;166;226;46m                 );[48;2;0;40;0m                                                           
[48;2;0;40;0m[38;2;166;226;46m             });[48;2;0;40;0m                                                              
[48;2;0;40;0m[38;2;166;226;46m         });[48;2;0;40;0m                                                                  
[48;2;0;40;0m[38;2;166;226;46m [48;2;0;40;0m                                                                             
[48;2;0;40;0m[38;2;166;226;46m         context([48;2;0;40;0m[38;2;230;219;116m"when comparing the same jQuery object"[48;2;0;40;0m[38;2;166;226;46m, [48;2;0;40;0m[38;2;102;217;239mfunction[48;2;0;40;0m[38;2;166;226;46m() {[48;2;0;40;0m        
[48;2;0;40;0m[38;2;166;226;46m             it([48;2;0;40;0m[38;2;230;219;116m"should return true"[48;2;0;40;0m[38;2;166;226;46m, [48;2;0;40;0m[38;2;102;217;239mfunction[48;2;0;40;0m[38;2;166;226;46m() {[48;2;0;40;0m                            
[48;2;0;40;0m[38;2;166;226;46m                 [48;2;0;40;0m[38;2;102;217;239mvar[48;2;0;40;0m[38;2;166;226;46m [48;2;0;40;0m[38;2;255;255;255m$head[48;2;0;40;0m[38;2;166;226;46m [48;2;0;40;0m[38;2;249;38;114m=[48;2;0;40;0m[38;2;166;226;46m jQuery([48;2;0;40;0m[38;2;230;219;116m"head"[48;2;0;40;0m[38;2;166;226;46m);[48;2;0;40;0m                                  
[48;2;0;40;0m[38;2;166;226;46m [48;2;0;40;0m                                                                             
[48;2;0;40;0m[38;2;166;226;46m                 [48;2;0;40;0m[38;2;255;255;255massert[48;2;0;40;0m[38;2;166;226;46m.isTrue([48;2;0;40;0m[38;2;255;255;255msamsam[48;2;0;40;0m[38;2;166;226;46m.deepEqual([48;2;0;40;0m[38;2;255;255;255m$head[48;2;0;40;0m[38;2;166;226;46m, [48;2;0;40;0m[38;2;255;255;255m$head[48;2;0;40;0m[38;2;166;226;46m));[48;2;0;40;0m               
[48;2;0;40;0m[38;2;166;226;46m             });[48;2;0;40;0m                                                              
[48;2;0;40;0m[38;2;166;226;46m         });[48;2;0;40;0m                                                                  
[48;2;0;40;0m[38;2;166;226;46m     });[48;2;0;40;0m                                                                      
[48;2;0;40;0m[38;2;166;226;46m }[48;2;0;40;0m[38;2;248;248;242m);[48;2;0;40;0m                                                                          

[34mpackage-lock.json[0m
[34m────────────────────────────────────────────────────────────────────────────────[0m
[34m4719[0m
[38;2;248;248;242m         [38;2;230;219;116m"handlebars"[38;2;248;248;242m: [38;2;230;219;116m"^4.1.2"[38;2;248;248;242m                                               
[38;2;248;248;242m       }                                                                      
[38;2;248;248;242m     },                                                                       
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic
   7: <syntect::highlighting::highlighter::HighlightIterator as core::iter::traits::iterator::Iterator>::next
   8: <syntect::highlighting::highlighter::HighlightIterator as core::iter::traits::iterator::Iterator>::next
   9: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  10: syntect::easy::HighlightLines::highlight
  11: delta::paint::Painter::paint_buffered_lines
  12: delta::delta::handle_hunk_line
  13: delta::delta::delta
  14: delta::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
  18: std::rt::lang_start_internal
  19: main
```

**Comment by dandavison** [comment]
Thanks, that's working for me (MacOS Mojave). What's your OS? Is it MacOS Catalina?

**Comment by mgred** [comment]
> What's your OS? Is it MacOS Catalina?

Same here, macOS Mojave - 10.14.6

**Comment by dandavison** [comment]
Does the version from homebrew work for you? (`brew install git-delta` seeing as you are not on MacOS Catalina; for Catalina the public homebrew build are currently broken and so one should use `brew tap dandavison/delta https://github.com/dandavison/delta; brew install dandavison/delta/git-delta`)

**Comment by mgred** [comment]
> Does the version from homebrew work for you?

Just tested the above commands and with that version it seems to work.

**Comment by dandavison** [comment]
Hm! So if you did want to continue investigating, you could look at `delta --version` for the one that _is_ working, and then check out the git tag corresponding to that version in the repo and rebuild locally, and see if your local build still doesn't work. It would be nice to know what's going wrong.

**Comment by mgred** [comment]
Ok, let me check 👍

**Comment by dandavison** [comment]
@mgred is it working for you now, ok to close this?

**Comment by mgred** [comment]
@dandavison thanks for the ping! It's still buggy for me, I hadn't have the time to investigate further. Let me post some updates during the weekend. ok?

**Comment by dandavison** [comment]
That would be great, thanks!

**Comment by mgred** [comment]
Hey @dandavison, sorry for my late answer and thanks for you patience 💯 

As you suggested I jumped back on the history to several tags (0.0.14..12) and rebuilt with `cargo build --release`, so far I had the same problem with all of the builds.

My specific steps are:
* `git checkout f702874 # this is verion 0.0.14` or any other commit of a tag
* `cargo build --release`
* `cp target/release/delta ~/.cargo/bin`

So far I can tell, that it seems to have problems with JSON files, as it always stops working on `package-lock.json` in a JS project.

I created a test repo with a JSON that shows the error as well when diffing 2 commits https://github.com/mgred/delta-test

As before, when I install the latest version from homebrew (`brew tap dandavison/delta https://github.com/dandavison/delta; brew install dandavison/delta/git-delta`) which is `0.0.14`, it works with the same JSON file 🙃 

Am I doing something wrong when installing the binary locally, is there any dependency missing, maybe?! Sorry I'm really fresh to rust 😅 

Please let me know how I can further help to find outs what's wrong here.

**Comment by dandavison** [comment]
Thanks @mgred! I've followed your steps and it's still not crashing for me. Do you use `rustup` to manage your rust development environment? If so, what does `rustup show` output? Mine is below. I wonder whether `rustup update` might fix the problem on your system. (Do you still get the crash when you do `cargo build` and use the executable at `target/debug/delta`?)

```
$ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/dan/.rustup

stable-x86_64-apple-darwin (default)
rustc 1.39.0 (4560ea788 2019-11-04)
```

**Comment by mgred** [comment]
hey @dandavison 

> Do you use `rustup` to manage your rust development environment? If so, what does `rustup show` output? Mine is below. I wonder whether `rustup update` might fix the problem on your system.

I have `rustup` installed and `rustup show` outputs the same as on you machine 👍 

> (Do you still get the crash when you do `cargo build` and use the executable at `target/debug/delta`?)

Now it's getting even crazier: I rebuild again with `cargo build --release` and copied a binary from `target/debug` (I later noticed that the `--release` option does not output anything into the `debug` directory). This binary was from a previous build, but I did not track the version 🤦‍♂ and guess what: This version worked 🎉 

I run `cargo clean` to make a fresh build with `cargo build`❗️this time and copied again  from the `target/debug` folder and now I get the same error with this binaries again 😖
I also jumed back in the history some version and tried the binaries from `target/debug`, same error.

**Comment by dandavison** [comment]
Hm. Have you tried  `rustup update`?

**Comment by mgred** [comment]
> Hm. Have you tried `rustup update`?

Yes, I did already

I was playing around and just did `cargo update`. It fetched some new dependecies. I then rebuild with `cargo build --release` and everyting now works as expected 👍 💯
Seems I built the package with outdated deps 🤦‍♂ 

Thanks alot for your help and effort and in general for this awesome tool 🤓
