### ISSUE TITLE
🐛 Panic/crash when diffing Vue files with pug syntax in the template

### ISSUE THREAD

**Issue by CodeGradox** [dandavison/delta#634]
Delta crashes when diffing a Vue file with uses the pug template engine.
```
[~/projects/delta-vue-bug] > (master) RUST_BACKTRACE=full git diff
thread 'main' panicked at 'Can only call resolve on linked references: ByScope { scope: <text.pug>, sub_context: None }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/syntect-4.5.0/src/parsing/syntax_definition.rs:191:18
stack backtrace:

App.vue

───┐
1: │
───┘
0:     0x559b27eff4e0 - <unknown>
   1:     0x559b27f204ef - <unknown>
   2:     0x559b27efbff2 - <unknown>
   3:     0x559b27f01645 - <unknown>
   4:     0x559b27f010f3 - <unknown>
   5:     0x559b27f01c4d - <unknown>
   6:     0x559b27f017e7 - <unknown>
   7:     0x559b27eff99c - <unknown>
   8:     0x559b27f01749 - <unknown>
   9:     0x559b27ce188b - <unknown>
  10:     0x559b27e7c0c2 - <unknown>
  11:     0x559b27e7a8f8 - <unknown>
  12:     0x559b27e71888 - <unknown>
  13:     0x559b27d010c1 - <unknown>
  14:     0x559b27cfed54 - <unknown>
  15:     0x559b27d53d09 - <unknown>
  16:     0x559b27d514d2 - <unknown>
  17:     0x559b27d6fbee - <unknown>
  18:     0x559b27d7220c - <unknown>
  19:     0x559b27d22c53 - <unknown>
  20:     0x559b27d233b9 - <unknown>
  21:     0x559b27f0214a - <unknown>
  22:     0x559b27d768e2 - <unknown>
  23:     0x7f4ab34ccb25 - __libc_start_main
  24:     0x559b27ce293e - <unknown>
  25:                0x0 - <unknown>
```

Delta is setup like this in `~/.gitconfig`
```
[core]
  pager = delta --light
```

To reproduce simply create a new folder and init git. Then add the following Vue file and commit it. Finally, you add a change to code inside the `<template>` tag and run `git diff`.
```vue
<template lang="pug">
p
  | Hello world
</template>

<script>
export default {}
</script>
```
Changing anything inside the `<script>` tag does not cause a panic. Delta  does not panic if I remove the `lang="pug"` from the `<template>` tag.

**Comment by dandavison** [comment]
@sharkdp would you mind suggesting next steps here? (I know you have experience with several similar issues). The example code fragment below, when named with a `.vue` suffix, crashes bat, and delta, and syncat. I'm not quite sure whose the bug is -- is it in the syntax definition repo? 

---------------

@CodeGradox -- thanks. I believe this is a bug in an upstream library, but I am not sure whether it is in https://github.com/vuejs/vue-syntax-highlight or https://github.com/trishume/syntect, or both. Your example file also crashes [bat](https://github.com/sharkdp/bat) which, like delta, uses syntect for syntax highlighting. The bug can be reproduced in the syntect repo, using the syntax definition file from bat, with a line like this:

```
$ cargo run --example syncat -- --extra-syntaxes $BAT_REPO/assets/syntaxes/02_Extra/Vue delta-634-crash.vue
thread 'main' panicked at 'Can only call resolve on linked references: ByScope { scope: <text.pug>, sub_context: None }', src/parsing/syntax_definition.rs:191:18
```

where `delta-634-crash.vue` contains

```vue
<template lang="pug">
hello
</template>
```

I think that syntect [does not](https://github.com/trishume/syntect/issues/248#issuecomment-482146524) promise never to panic with any user syntax definition, therefore this is not necessarily a bug in syntect. bat looks to be running the current HEAD of the `newsyntax-3.3.6` branch, so unfortunately it may not be as simple as just updating the Vue syntax definitions in the bat repo: https://github.com/sharkdp/bat (delta copies the syntax files from bat).



```
   0: rust_begin_unwind
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974/library/std/src/panicking.rs:435:5
   2: syntect::parsing::parser::ParseState::push_meta_ops
   3: syntect::parsing::parser::ParseState::parse_line
   4: syntect::easy::HighlightLines::highlight
   5: delta::paint::Painter::get_syntax_style_sections_for_lines
   6: delta::paint::Painter::paint_buffered_minus_and_plus_lines
   7: delta::delta::delta
   8: delta::run_app
   9: delta::main
```

**Comment by dandavison** [comment]
I see that something like this is fine (e.g. does not crash bat)

```vue
<template lang="pugxxx">
hello
</template>
```

but valid references such as `lang="pug"` and `lang="jade"` both do cause the crash.

**Comment by sharkdp** [comment]
@dandavison Thank you for the mention. Some possible next steps are discussed in this ticket: https://github.com/sharkdp/bat/issues/915.

In particular, see [this comment](https://github.com/sharkdp/bat/issues/915#issuecomment-823581511) by @keith-hall. The tracking issue to fix this in `bat` is here: https://github.com/sharkdp/bat/issues/1616

**Comment by sharkdp** [comment]
@dandavison FYI: https://github.com/sharkdp/bat/pull/1771

**Comment by dandavison** [comment]
@hedefalk bat and syntect contributors are working on this, see https://github.com/sharkdp/bat/issues/915. Currently the demo Vue file still crashes bat, so I think we should follow / help with their work, and then adopt their solution.
