### ISSUE TITLE
panic for certain unicode code points when rendering patch 🐛 

### ISSUE THREAD

**Issue by rcousineau-xandr** [dandavison/delta#677]
I noticed this panic when doing a `git log -p` to read patch history for files under a specific directory. 

```
thread 'main' panicked at 'byte index 1568 is not a char boundary; it is inside 'ݶ' (bytes 1567..1569) of `+Q����'php-code-coverage/Report/Xml/Method.phpW�}[W�        \�(php-code-coverage/Report/Html/Facade.phpD�}[D$�fɶ*php-code-coverage/Report/Html/Renderer.phpp"�}[p"'�i?�`[...]', /Users/rcousineau/.cargo/registry/src/github.com-1ecc6299db9ec823/git-delta-0.7.1/src/ansi/mod.rs:115:34
stack backtrace:
   0:        0x10e65e2a4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h18cc31b07c2f1a67
   1:        0x10e67ba5d - core::fmt::write::h24f8349e8e89c9af
   2:        0x10e65a826 - std::io::Write::write_fmt::hc54d7d6e95b15753
   3:        0x10e6600b9 - std::panicking::default_hook::{{closure}}::h11b550d560f5cc66
   4:        0x10e65fc49 - std::panicking::default_hook::he168e99d1cf91c3c
   5:        0x10e66073b - std::panicking::rust_panic_with_hook::hf87bfc4afef21ea6
   6:        0x10e660265 - std::panicking::begin_panic_handler::{{closure}}::h19ac9cd24a19b238
   7:        0x10e65e748 - std::sys_common::backtrace::__rust_end_short_backtrace::h5fc3f41df3517232
   8:        0x10e6601ca - _rust_begin_unwind
   9:        0x10e68c54f - core::panicking::panic_fmt::habd0855285375977
  10:        0x10e68cb2b - core::str::slice_error_fail::h011de3d9f204cc8e
  11:        0x10e4cc029 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h1d8790d11fd610bc
  12:        0x10e43e843 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::hf163e1212dcf56c7
  13:        0x10e4cc5f0 - core::iter::traits::iterator::Iterator::collect::h4ccee5d66be66b88
  14:        0x10e4cf25a - delta::ansi::truncate_str::h7fec19b702d5905e
  15:        0x10e49c192 - delta::delta::StateMachine::ingest_line::hb4739695dcf839c4
  16:        0x10e49b6ad - delta::delta::delta::heee04fad397d393d
  17:        0x10e4b54ee - delta::run_app::he9b0e826909a0cfa
  18:        0x10e4b7601 - delta::main::hf1cdc26dc31ea317
  19:        0x10e482eda - std::sys_common::backtrace::__rust_begin_short_backtrace::h4af2b95ca649ddf2
  20:        0x10e4835ec - std::rt::lang_start::{{closure}}::h9a51a4f861a350ed
  21:        0x10e660b94 - std::rt::lang_start_internal::h86f505dc7de50d93
  22:        0x10e4bc459 - _main
...skipping...
```

I ran the same command with `-c core.pager=less` and it seems to happen while reading a `phar` file, which is a php archive that seems to contain text *and* binary data. So I wasn't really intending to try to read the contents of this file in the log... And this might be a non-issue.

**Comment by dandavison** [comment]
Thanks @rcousineau-xandr, delta shouldn't crash, so I agree there's a bug in something (probably delta!). I don't have experience of working with arabic and I see that when [ݶ](https://graphemica.com/%DD%B6) is inserted into text editors it has some right-to-left behaviour. So I think I need to Anyway, this was introducing some friction into debugging! `truncate_str` [does have](https://github.com/dandavison/delta/blob/d29bf95767d6b03075ac6382ce8e2034fd753725/src/ansi/console_tests.rs#L57) test coverage involving multi-byte utf-8 characters, and I just added a simple test using ݶ in ad52c74, but I think I need to learn more about writing unit tests with RTL characters, or perhaps someone can help here.

**Comment by rcousineau-xandr** [comment]
yeah, I don't think there was an actual ݶ character. rather, within a binary blob there just *happened* to be that sequence of bytes. I'm not sure what the appropriate behavior should be when delta attempts to print binary data to the screen...

**Comment by robinmoussu** [comment]
I think I have the same issue. This is due to an "*.ai" file (some image created by photoshop) that is displayed as if it was a text-file (and not a binary file).

```
��bx��E���B�;����`[...]', /Users/robinm/.cargo/registry/src/github.com-1ecc6299db9ec823/git-delta-0.9.2/src/ansi/mod.rs:116:34թ��8_�٥ʨQ����Q�j@�&�A)/��g�>'K���t�;\��
stack backtrace:
   0:        0x10d3236c1 - std::backtrace_rs::backtrace::libunwind::trace::h6846e1b4a24fa52a
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10d3236c1 - std::backtrace_rs::backtrace::trace_unsynchronized::hf681a8e60b9d56b5
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10d3236c1 - std::sys_common::backtrace::_print_fmt::h4a2792baa0b5234a
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x10d3236c1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9c9c2c58a5e55211
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x10d3418db - core::fmt::write::h2d5ecb4b9764759c
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/fmt/mod.rs:1149:17
   5:        0x10d31f9aa - std::io::Write::write_fmt::hbb2ed9492eac32a2
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/io/mod.rs:1697:15
   6:        0x10d324ef5 - std::sys_common::backtrace::_print::hce4ddf171e645ac1
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x10d324ef5 - std::sys_common::backtrace::print::hdbe533a855ab9e20
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x10d324ef5 - std::panicking::default_hook::{{closure}}::h39365228a3bf0aa2
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:211:50
   9:        0x10d324adf - std::panicking::default_hook::h8ca622aa16a42db0
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:228:9
  10:        0x10d3255e0 - std::panicking::rust_panic_with_hook::ha8b89b2b3829767b
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:606:17
  11:        0x10d32507e - std::panicking::begin_panic_handler::{{closure}}::h92845c1f420a7f41
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:502:13
  12:        0x10d323b47 - std::sys_common::backtrace::__rust_end_short_backtrace::hdae352311dc8769f
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/sys_common/backtrace.rs:139:18
  13:        0x10d324fea - rust_begin_unwind
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:498:5
  14:        0x10d354baf - core::panicking::panic_fmt::h88a1b6fbb9084d2c
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/panicking.rs:106:14
  15:        0x10d35528d - core::str::slice_error_fail::h75b5adf3a88db9cf
  16:        0x10d140467 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::h8b5997a903c84e82
  17:        0x10d10a504 - delta::ansi::strip_ansi_codes::hfae865fab4358c76
  18:        0x10d17ae5b - delta::delta::StateMachine::ingest_line::h5ef64db805748326
  19:        0x10d179fc1 - delta::delta::delta::h302fbcde16e40686
  20:        0x10d0fcd04 - delta::main::h30a662a842ff6950
  21:        0x10d1693b6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1237dcb5ba69216c
  22:        0x10d15251c - std::rt::lang_start::{{closure}}::h2f2c6e26fb989806
  23:        0x10d322f24 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h8bdfac87c3454a63
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/core/src/ops/function.rs:259:13
  24:        0x10d322f24 - std::panicking::try::do_call::h8de6f533093685b1
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:406:40
  25:        0x10d322f24 - std::panicking::try::ha08a65edccf4960d
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:370:19
  26:        0x10d322f24 - std::panic::catch_unwind::h3615b53d47a6bffb
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panic.rs:133:14
  27:        0x10d322f24 - std::rt::lang_start_internal::{{closure}}::hd57ce1a0d4220178
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/rt.rs:128:48
  28:        0x10d322f24 - std::panicking::try::do_call::h0fe0c5863a433cdd
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:406:40
  29:        0x10d322f24 - std::panicking::try::hb547e00445c5dd3d
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panicking.rs:370:19
  30:        0x10d322f24 - std::panic::catch_unwind::h8b35d4f26df8f6bd
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/panic.rs:133:14
  31:        0x10d322f24 - std::rt::lang_start_internal::h05aa3173240f4b0d
                               at /rustc/0727994435c75fdedd3e9d226cf434089b0ab585/library/std/src/rt.rs:128:20
  32:        0x10d0fd1d9 - _main
```

I had the issue with version v0.7.1 and updated v0.9.2 and still have the issue.

Even though delta seems to have crashed, less is still reactive.

**Comment by dandavison** [comment]
Thanks @robinmoussu, sorry to be slow to respond. Can anyone give me instructions to reproduce this crash? How do I make a repo in which a binary file is treated as text by git? Do you have examples in a public repo, or a repo that you can share? Or do you have a suitable file that you can attach?

**Comment by robinmoussu** [comment]
Unfortunately, I don't have anything public, nor a photoshop licence to generate a `.ai` file. I will try to create one with gimp (I don't know if it's possible). Otherwise I will try to create a text file with embeded binary with `cat some_file.txt some_binary > text_file_with_binary.txt`, or by using an hexadecimal editor directly. My schedule is ultra busy, I don't know when I will have time to do it.

**Comment by dandavison** [comment]
> Otherwise I will try to create a text file with embeded binary with cat some_file.txt some_binary > text_file_with_binary.txt, or by using an hexadecimal editor directly. My schedule is ultra busy, I don't know when I will have time to do it.

You've done it already! Thanks very much:

```
$ cat src/delta.rs target/release/delta > src/binary.rs
$ git add src/binary.rs
$ git diff --cached
:thread 'main' panicked at 'byte index 1076 is not a char boundary; it is inside '�' (bytes 1074..1077) of `>`-H������A�H�u��ϱ*L��`���H�]�H�H��x���L������L������H������H������H�����H��H���L����H�����H�� ���H`[...]', src/ansi/mod.rs:146:34
```

**Comment by jyn514** [comment]
I ran into this same crash on a text file without binary.
```
quiche/src/build.rs
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

thread 'main' panicked at 'byte index 25 is not a char boundary; it is inside '�' (bytes 24..27) of `-'��
                                                                                                         ���
                                                                                                            `', /home/jnelson/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/git-delta-0.12.0/src/ansi/mod.rs:146:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The diff without delta was
```
diff --git a/quiche/src/build.rs b/quiche/src/build.rs
index d1ef4f4e..e675bfed 100644
--- a/quiche/src/build.rs
+++ b/quiche/src/build.rs
@@ -217,7 +217,9 @@ fn target_dir_path() -> std::path::PathBuf {
 }
 
 fn main() {
-    if cfg!(feature = "boringssl-vendored") && !cfg!(feature = "boring-sys") {
+    if cfg!(feature = "boringssl-vendored") &&
+        !cfg!(feature = "boringssl-boring-crate")
+    {
         let bssl_dir = std::env::var("QUICHE_BSSL_PATH").unwrap_or_else(|_| {
             let mut cfg = get_boringssl_cmake_config();
 
@@ -237,7 +239,7 @@ fn main() {
         println!("cargo:rustc-link-lib=static=ssl");
     }
 
-    if cfg!(feature = "boring-sys") {
+    if cfg!(feature = "boringssl-boring-crate") {
         println!("cargo:rustc-link-lib=static=crypto");
         println!("cargo:rustc-link-lib=static=ssl");
     }
diff --git a/quiche/src/lib.rs b/quiche/src
```

**Comment by martinetd** [comment]
hi @dandavison 
I've had crash and could trim it down to a reasonably small git log (it's also a binary, someone added a pdf file in their git and `git log -p` displayed garbage...)

The backtrace looks similar enough to previous ones:

```
src/ansi/mod.rs:148:34
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.59.0/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.59.0/library/core/src/panicking.rs:116:14
   2: core::str::slice_error_fail
   3: core::str::traits::<impl core::slice::index::SliceIndex<str> for core::ops::range::Range<usize>>::index
             at /usr/src/rustc-1.59.0/library/core/src/str/traits.rs:214:21
   4: core::str::traits::<impl core::ops::index::Index<I> for str>::index
             at /usr/src/rustc-1.59.0/library/core/src/str/traits.rs:64:9
   5: delta::ansi::ansi_strings_iterator::{{closure}}
             at /home/martinet/code/delta/src/ansi/mod.rs:148:34
   6: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /usr/src/rustc-1.59.0/library/core/src/ops/function.rs:280:13
   7: core::option::Option<T>::map
             at /usr/src/rustc-1.59.0/library/core/src/option.rs:883:29
   8: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /usr/src/rustc-1.59.0/library/core/src/iter/adapters/map.rs:103:9
   9: alloc::vec::Vec<T,A>::extend_desugared
             at /usr/src/rustc-1.59.0/library/alloc/src/vec/mod.rs:2638:35
  10: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /usr/src/rustc-1.59.0/library/alloc/src/vec/spec_extend.rs:18:9
  11: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /usr/src/rustc-1.59.0/library/alloc/src/vec/spec_from_iter_nested.rs:37:9
  12: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /usr/src/rustc-1.59.0/library/alloc/src/vec/spec_from_iter.rs:33:9
  13: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /usr/src/rustc-1.59.0/library/alloc/src/vec/mod.rs:2541:9
  14: core::iter::traits::iterator::Iterator::collect
             at /usr/src/rustc-1.59.0/library/core/src/iter/traits/iterator.rs:1745:9
  15: delta::ansi::truncate_str
             at /home/martinet/code/delta/src/ansi/mod.rs:38:17
  16: delta::delta::StateMachine::ingest_line
             at /home/martinet/code/delta/src/delta.rs:204:29
  17: delta::delta::StateMachine::consume
             at /home/martinet/code/delta/src/delta.rs:147:13
  18: delta::delta::delta
             at /home/martinet/code/delta/src/delta.rs:118:5
  19: delta::run_app
             at /home/martinet/code/delta/src/main.rs:154:25
  20: delta::main
             at /home/martinet/code/delta/src/main.rs:78:21
  21: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.59.0/library/core/src/ops/function.rs:227:5
```

Here's the file this reproduces on (100KB):
[delta-repro.txt](https://github.com/dandavison/delta/files/9024995/delta-repro.txt)
just running `delta < dela-repro.txt`  fails immediately for me.

I however wouldn't know what to do other than to put the `ansi_strings_iterator(s).collect` call in a `panic::catch_unwind` statement, so I'll leave the actual resolution to you. Should hopefully be easier with a reproducer :)

Thanks!

**Comment by dandavison** [comment]
Thanks @martinetd, that's really helpful.

**Comment by dandavison** [comment]
Thanks everyone, this should be fixed in master now. If anyone's able to confirm that would be great. (The bug I've fixed is that delta was trying to do ANSI sequence processing on UTF8 strings created from binary input -- but these occasionally contain sequences of bytes that look like ANSI sequences and cause the ANSI parser to crash.)

**Comment by martinetd** [comment]
Thanks! I can confirm this no longer reproduces on the repo I was looking at, at least :)

FWIW I was looking at https://rust-fuzz.github.io/book/ and delta might be a good target for this if I figure out how to instantiate a config and writer in an external crate (when I tried briefly the other day it complained about delta not having a lib target, and I'm pretty sure `integration_test_utils::make_config_from_args_and_git_config` wouldn't be exported...) -- if I ever find time to finish this I'll open a new issue with any reproducer found and/or PR integrating new tests. Don't hold your breath though, that might never happen...
